sudo: false
dist: trusty

language: python
python:
    - "3.6"

install:
    - "pip install -r requirements_dev.txt"
script:
    - black --check *.py */
    - isort --check-only --recursive *.py */
    - "flake8 ."
